# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b066837059af97425ab62c7b95bf8aa56bbccacba804cfaaeeac523c42bb088fe420bbd06180b5b3ecec7da288b3ef8398af200eadf811944f7556c7e49db001

test:
  secret_key_base: af441082ab573c63e47ecdb03b6e0d8ff3d2fd8b95bacb4f177845541322b6ede9bbf7270e6440219cb84e9bbfcc375fdb92080af6378b5e6d9247031551edb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
